/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aoindustries_io_unix_UnixFile */

#ifndef _Included_com_aoindustries_io_unix_UnixFile
#define _Included_com_aoindustries_io_unix_UnixFile
#ifdef __cplusplus
extern "C" {
#endif
#undef com_aoindustries_io_unix_UnixFile_MINIMUM_USER_UID
#define com_aoindustries_io_unix_UnixFile_MINIMUM_USER_UID 500L
#undef com_aoindustries_io_unix_UnixFile_MINIMUM_USER_GID
#define com_aoindustries_io_unix_UnixFile_MINIMUM_USER_GID 500L
#undef com_aoindustries_io_unix_UnixFile_ROOT_UID
#define com_aoindustries_io_unix_UnixFile_ROOT_UID 0L
#undef com_aoindustries_io_unix_UnixFile_ROOT_GID
#define com_aoindustries_io_unix_UnixFile_ROOT_GID 0L
#undef com_aoindustries_io_unix_UnixFile_PERMISSION_MASK
#define com_aoindustries_io_unix_UnixFile_PERMISSION_MASK 4095LL
#undef com_aoindustries_io_unix_UnixFile_OTHER_EXECUTE
#define com_aoindustries_io_unix_UnixFile_OTHER_EXECUTE 1LL
#undef com_aoindustries_io_unix_UnixFile_OTHER_WRITE
#define com_aoindustries_io_unix_UnixFile_OTHER_WRITE 2LL
#undef com_aoindustries_io_unix_UnixFile_OTHER_READ
#define com_aoindustries_io_unix_UnixFile_OTHER_READ 4LL
#undef com_aoindustries_io_unix_UnixFile_GROUP_EXECUTE
#define com_aoindustries_io_unix_UnixFile_GROUP_EXECUTE 8LL
#undef com_aoindustries_io_unix_UnixFile_GROUP_WRITE
#define com_aoindustries_io_unix_UnixFile_GROUP_WRITE 16LL
#undef com_aoindustries_io_unix_UnixFile_GROUP_READ
#define com_aoindustries_io_unix_UnixFile_GROUP_READ 32LL
#undef com_aoindustries_io_unix_UnixFile_USER_EXECUTE
#define com_aoindustries_io_unix_UnixFile_USER_EXECUTE 64LL
#undef com_aoindustries_io_unix_UnixFile_USER_WRITE
#define com_aoindustries_io_unix_UnixFile_USER_WRITE 128LL
#undef com_aoindustries_io_unix_UnixFile_USER_READ
#define com_aoindustries_io_unix_UnixFile_USER_READ 256LL
#undef com_aoindustries_io_unix_UnixFile_SAVE_TEXT_IMAGE
#define com_aoindustries_io_unix_UnixFile_SAVE_TEXT_IMAGE 512LL
#undef com_aoindustries_io_unix_UnixFile_SET_GID
#define com_aoindustries_io_unix_UnixFile_SET_GID 1024LL
#undef com_aoindustries_io_unix_UnixFile_SET_UID
#define com_aoindustries_io_unix_UnixFile_SET_UID 2048LL
#undef com_aoindustries_io_unix_UnixFile_TYPE_MASK
#define com_aoindustries_io_unix_UnixFile_TYPE_MASK 61440LL
#undef com_aoindustries_io_unix_UnixFile_IS_FIFO
#define com_aoindustries_io_unix_UnixFile_IS_FIFO 4096LL
#undef com_aoindustries_io_unix_UnixFile_IS_CHARACTER_DEVICE
#define com_aoindustries_io_unix_UnixFile_IS_CHARACTER_DEVICE 8192LL
#undef com_aoindustries_io_unix_UnixFile_IS_DIRECTORY
#define com_aoindustries_io_unix_UnixFile_IS_DIRECTORY 16384LL
#undef com_aoindustries_io_unix_UnixFile_IS_BLOCK_DEVICE
#define com_aoindustries_io_unix_UnixFile_IS_BLOCK_DEVICE 24576LL
#undef com_aoindustries_io_unix_UnixFile_IS_REGULAR_FILE
#define com_aoindustries_io_unix_UnixFile_IS_REGULAR_FILE 32768LL
#undef com_aoindustries_io_unix_UnixFile_IS_SYM_LINK
#define com_aoindustries_io_unix_UnixFile_IS_SYM_LINK 40960LL
#undef com_aoindustries_io_unix_UnixFile_IS_SOCKET
#define com_aoindustries_io_unix_UnixFile_IS_SOCKET 49152LL
/* Inaccessible static: loaded */
/* Inaccessible static: random */
/* Inaccessible static: class_00024com_00024aoindustries_00024io_00024unix_00024UnixFile */
/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    chown0
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_chown0
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    crypt0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoindustries_io_unix_UnixFile_crypt0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getAccessTime0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getAccessTime0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getBlockCount0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getBlockCount0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getBlockSize0
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_aoindustries_io_unix_UnixFile_getBlockSize0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getChangeTime0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getChangeTime0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getDevice0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getDevice0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getDeviceIdentifier0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getDeviceIdentifier0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getGID0
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_aoindustries_io_unix_UnixFile_getGID0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getInode0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getInode0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getLinkCount0
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_aoindustries_io_unix_UnixFile_getLinkCount0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getMode0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getMode0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getModifyTime0
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_aoindustries_io_unix_UnixFile_getModifyTime0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    mktemp0
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoindustries_io_unix_UnixFile_mktemp0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getUID0
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_aoindustries_io_unix_UnixFile_getUID0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    mknod0
 * Signature: ([BJJ)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_mknod0
  (JNIEnv *, jclass, jbyteArray, jlong, jlong);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    mkfifo0
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_mkfifo0
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    setMode0
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_setMode0
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    symLink0
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_symLink0
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    link0
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_link0
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    readLink0
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_aoindustries_io_unix_UnixFile_readLink0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    utime0
 * Signature: ([BJJ)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_utime0
  (JNIEnv *, jclass, jbyteArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
